server:
  port: 8000

spring:
  application:
     name: api-gateway-zuul
    
zuul:
    routes:
     admin-security:
      url: http://localhost:8286
     user-security:
      url: http://localhost:8682
     payment-service:
      url: http://localhost:8004 
     ticket-reservation-service:
      url: http://localhost:8003
     train-service:
      url: http://localhost:8002
      
      
eureka:
   client:
    register-with-eureka: true
    fetch-registry: true
    
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
    hostname: localhost
